### ISSUE TITLE
discussion: long-term performance on a "bigger" usage scale

### ISSUE THREAD

**Issue by guzzisti** [flokX/devShort#16]
Has anyone had *devShort* running over a longer period of time with a larger number of shortlinks defined?

As the stats for all shortlinks are stored in a single file `stats.json` this file will grow over time and may become a bottleneck as it needs to be read & decoded then encoded & written back on every redirect.

I wonder if there are any performance impacts over time when the stats sum up for a lager number of redirects. I'm aware that the overall data size will most likely still be measured in kilobytes, so maybe i'm a bit exaggerating. ;)

**Comment by flokX** [comment]
I already thought about this problem. Outgoing from your issue, I runned a few test.

Here are two examples:
4 shortlinks, 392 dates: 37ms redirect
9 shortlinks, 3320 dates: 68ms redirect

When the number of data points grows, there is a performance deterioration, which is not dramatically. Since devShorts is not a URL shortener for thousands of shortlinks and accesses I think there shouldn't be a problem. In my opinion the principal that devShort should be fully configurable and usable via the config.json and stats.json is in this context more important than the performance gains when using a database system.

The easiest performance tweak would be not to save the stats.json file as the beautified version to reduce the file size. However, this would result in a bad user experience when accessing this file via an editor.
